version: "3.8"

services:
  mysql:
    image: mysql:latest
    volumes:
      - ./mysql/sql/:/docker-entrypoint-initdb.d/
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: QUANLYVI
      MYSQL_USER: sa
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_HOST: '%'